export class Business {
    constructor(public businessId:string,
                public name: string,
                public logo:string,
                public email?: string,
                public phoneNumbers?: string[],
                public workingDays?: string[],
                public workingHours? :{ "from" :string,"to" :string},
                public address ?: string,
                public location?:{"address":string,"city":string,"coordinates":number[]},
                public tags?:string[],
                public category?:string,
                public description?:string,
                public interactivity?:number,
                public totalsRatings?:number,
                public photos?:string[],
                public paymentRequired?:number,
                public deposit?:number,
                ) {}
}